//id, autogenerated, title, content, summary, image, date created, views, is_intl  etc

import {
  Column,
  CreateDateColumn,
  Entity,
  PrimaryGeneratedColumn,
} from 'typeorm';

@Entity()
export class ArticleEntity {
  @PrimaryGeneratedColumn('uuid')
  id: string;

  @CreateDateColumn()
  created: Date;

  @Column('text')
  title: string;

  @Column('text')
  content: string;

  @Column('boolean', { default: false })
  is_intl: boolean;
}
